apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: wallabag
  namespace: wallabag

resources:
  # Namespace and configuration
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  
  # PostgreSQL database
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  
  # Wallabag application
  - wallabag/pvc.yaml
  - wallabag/service.yaml
  - wallabag/deployment.yaml

commonLabels:
  app.kubernetes.io/name: wallabag
  app.kubernetes.io/instance: wallabag-homelab
  app.kubernetes.io/version: "2.6.9"
  app.kubernetes.io/managed-by: flux

namespace: wallabag