#cloud-config
users:
  - name: alex
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC... # Will be populated by Hetzner SSH key "alex@seven"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/zsh
    groups: sudo
  - name: root

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - zsh
  - tmux
  - unzip
  - build-essential
  - locales

runcmd:
  # Install Tailscale with proper error handling
  - echo "Installing Tailscale..." >> /var/log/cloud-init-debug.log
  - curl -fsSL https://tailscale.com/install.sh | sh
  - echo "Tailscale installed, starting service..." >> /var/log/cloud-init-debug.log
  - systemctl enable tailscaled
  - systemctl start tailscaled
  - sleep 10
  - echo "Connecting to Tailscale..." >> /var/log/cloud-init-debug.log
  - tailscale up --authkey=${tailscale_auth_key} --hostname=${hostname} --accept-routes --accept-dns
  - echo "Tailscale status:" >> /var/log/cloud-init-debug.log
  - tailscale status >> /var/log/cloud-init-debug.log

  # Install k3s control plane
  - echo "Installing k3s control plane..." >> /var/log/cloud-init-debug.log
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --node-ip=${private_ip} --advertise-address=${private_ip} --flannel-iface=enp7s0" sh -

  # Wait for k3s to be ready
  - sleep 30
  - until kubectl get nodes; do sleep 5; done
  - echo "k3s control plane ready" >> /var/log/cloud-init-debug.log

  # Setup dotfiles for alex user
  - echo "Setting up dotfiles..." >> /var/log/cloud-init-debug.log
  - sudo -u alex bash -c 'cd /home/alex && git clone https://github.com/alexbenisch/dotfiles.git'
  - sudo -u alex bash -c 'cd /home/alex/dotfiles && bash setup'
  - echo "Dotfiles setup complete" >> /var/log/cloud-init-debug.log
  
  # Change alex user shell to zsh
  - chsh -s /bin/zsh alex

write_files:
  - path: /etc/systemd/system/k3s.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/bin/k3s server --cluster-init --node-ip=${private_ip} --advertise-address=${private_ip} --flannel-iface=enp7s0

final_message: "k3s control plane setup complete"