apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path